---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - master
      - main
      - testing
      - dependabot/**
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
    tags_ignore:
      - '*'
  pull_request:
  pull_request_target:
  schedule:
    - cron: '25 13 13/13 * *'

  workflow_dispatch:

permissions: write-all

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Role
        uses: actions/checkout@v4
      - name: Run Ansible-lint
        uses: ansible/ansible-lint@v24.10.0
  test:
    needs:
      - lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "enterpriselinux"
            tag: "8"
          - image: "docker-molecule-images"
            tag: "buster"
          - image: "docker-molecule-images"
            tag: "bullseye"
          - image: "docker-molecule-images"
            tag: "fedora38"
          - image: "docker-molecule-images"
            tag: "fedora39"
          - image: "docker-molecule-images"
            tag: "fedora40"
          - image: "docker-molecule-images"
            tag: "opensuse"
          - image: "docker-molecule-images"
            tag: "jammy"
          - image: "docker-molecule-images"
            tag: "noble"
    steps:
      - name: Checkout Role
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Running Molecule Test
        uses: buluma/molecule-action@v24.6.17
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
      - name: Running Role Test
        run: ansible-galaxy role import --api-key ${{ secrets.galaxy_api_key }} buluma ${{ github.event.repository.name }}

  dependabot:
    needs:
      - lint
      - test
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'buluma' && github.event_name == 'pull_request'}}
    steps:
      - uses: "actions/checkout@master"
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Merge Dependabot PR"
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
